module.exports = {
  useEmoji: false,
  types: [
    { value: "feat", name: "feat:     new feature" },
    { value: "fix", name: "fix:      bug fix" },
    { value: "docs", name: "docs:     documentation changes" },
    { value: "style", name: "style:    formatting or stylistic changes" },
    { value: "refactor", name: "refactor: code change without feature/fix" },
    { value: "perf", name: "perf:     performance improvements" },
    { value: "test", name: "test:     adding or updating tests" },
    { value: "build", name: "build:    build system or dependency updates" },
    { value: "ci", name: "ci:       CI/CD pipeline changes" },
    { value: "chore", name: "chore:    maintenance work" },
    { value: "revert", name: "revert:   revert a previous commit" },
  ],
  messages: {
    type: "Select the type of change:",
    scope: "Optional scope (example: auth, ui, router):",
    subject: "Write a short, imperative summary:",
    body: "Provide a longer description (optional):",
    breaking: "List breaking changes (optional):",
    footerPrefixesSelect: "Select issue prefixes if needed:",
    customFooterPrefix: "Input custom footer prefix:",
    footer: "List issue references (optional):",
    confirmCommit: "Confirm commit?",
  },
  allowCustomScopes: true,
  allowEmptyScopes: true,
  skipQuestions: ["scope", "footerPrefix", "footer"],
  upperCaseSubject: false,
  markBreakingChangeMode: false,
  breaklineNumber: 100,
};
