name: Bug report
description: Report a reproducible bug
title: "bug: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug report. Please include enough detail to reproduce the issue.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened and what did you expect?
      placeholder: Concise description of the bug
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Please provide exact steps
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, browser, Bun version, app version/commit
      placeholder: Windows 11, Chrome 122, Bun 1.x, commit abc123
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Logs, screenshots, links, related issues
